version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Installer les dépendances
          command: pip install -r requirements.txt
      - run:
          name: Lancer un petit test
          command: python main.py
